<a href="https://colab.research.google.com/github/TyapkinaPA/-/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. Импортировать numpy и написать версию

numpy - библиотека с открытым исходным кодом для языка программирования Python.



In [ ]:
import numpy as np
#Версия numpy
print(np.__version__)

1.23.5


2. Создать нулевой вектор размера 10

In [ ]:
vektor_0 = np.zeros(10)
print(vektor_0)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


3. Создать вектор заполненный 7-ами размера 7

In [ ]:
vektor_7 = np.full(7, 7)
print(vektor_7)

[7 7 7 7 7 7 7]


4. Создать вектор заполненный четными числами от 10 до 100

In [ ]:
vector_chet = np.arange(10, 101, 2)
print(vector_chet)

[ 10  12  14  16  18  20  22  24  26  28  30  32  34  36  38  40  42  44
  46  48  50  52  54  56  58  60  62  64  66  68  70  72  74  76  78  80
  82  84  86  88  90  92  94  96  98 100]


5. Создать массив случайных чисел и развернуть его задом наперёд

In [ ]:
random_array = np.random.randn(5)
reversed_array = np.flip(random_array)
print(random_array)
print(reversed_array)

[-1.47205915  0.16896058  2.42628106 -1.37817245 -0.90944058]
[-0.90944058 -1.37817245  2.42628106  0.16896058 -1.47205915]


6. Создать двумерную матрицу размера 3 на 3, заполненную числами от 0 до 9

In [ ]:
matr = np.arange(9).reshape(3, 3)
print(matr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


7. Создать матрицу размера 4 на 4 с единицами на диагонали смещеной на один наверх.

In [ ]:
diagonal_matr = np.eye(4, k=-1)
print(diagonal_matr)

[[0. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]


8. Создать матрицу с числами в диапазоне от 1 до 4 по диагонали. В других ячейках матрицы должны быть семерки.

In [ ]:
custom_matr = np.diag([1, 2, 3, 4])
custom_matr[custom_matr == 0] = 7
print(custom_matr)

[[1 7 7 7]
 [7 2 7 7]
 [7 7 3 7]
 [7 7 7 4]]


9. Создать матрицу размера 5 на 5 заполненную чилами от 0 до 4 в строках.

In [ ]:
row_matr = np.tile(np.arange(5), (5, 1))
print(row_matr)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


10. Создать матрицу случайных чисел размера 10 на 10 и отнять среднее по строкам из каждого элемента строки

In [ ]:
random_matr = np.random.rand(10, 10)
mean_subtracted_matr = random_matr - np.mean(random_matr, axis=1, keepdims=True)
print(mean_subtracted_matr)

[[-0.30239623 -0.21398654 -0.061866   -0.23721175  0.46384498 -0.28531859
   0.00101393  0.41675357  0.42069649 -0.20152986]
 [-0.22492911 -0.33670586  0.39949954 -0.24029911 -0.37098559  0.01931732
   0.32361922  0.24565612  0.36982929 -0.18500182]
 [-0.39584304 -0.18715954 -0.20162962  0.39030681  0.21752706  0.28988876
  -0.41425704 -0.05910541  0.07571169  0.28456033]
 [ 0.15929919 -0.34742627 -0.11453575  0.234804   -0.30223465  0.23375391
   0.23213726  0.21539369  0.05828597 -0.36947734]
 [-0.22183891  0.05414464  0.23501655 -0.02253055  0.17371435  0.27792434
  -0.15953851 -0.24971206  0.24046919 -0.32764901]
 [ 0.3171395  -0.12874883 -0.07936055  0.01894838 -0.08390982  0.37785713
  -0.11496783 -0.01609083 -0.00127586 -0.28959128]
 [ 0.29398754  0.39026656  0.01801462  0.05192074 -0.05819258 -0.3754958
   0.37950495 -0.49391926 -0.47503694  0.26895017]
 [ 0.01366598 -0.21993111  0.34173878 -0.04812857  0.42908579  0.230952
  -0.32295395 -0.3036922  -0.02842627 -0.09231046]
 [-

11. Создать матрицу случайных чисел размера 10 на 10 и отнять медиану по столбцам из каждого элемента столбца

In [ ]:
random_matr = np.random.rand(10, 10)
median_subtracted_matr = random_matr - np.median(random_matr, axis=0, keepdims=True)
print(median_subtracted_matr)

[[-0.56313475  0.21395157  0.14598884  0.14740386 -0.25576964  0.24716435
   0.36377539  0.17713067 -0.41996817 -0.38453639]
 [-0.03950302 -0.06935923  0.12189584 -0.32337849 -0.12095823 -0.09874668
  -0.26765453  0.20545369  0.12181779 -0.37294087]
 [-0.55444849 -0.56385323 -0.30336608 -0.03271038 -0.3318396   0.02196182
  -0.45895062 -0.22796202 -0.10565218  0.13162819]
 [-0.15469454 -0.45093627  0.0781767   0.15543638 -0.10901484  0.08127297
  -0.27303653 -0.08659805  0.10565218 -0.04013457]
 [ 0.03950302  0.06935923 -0.50447931 -0.15256257  0.10901484 -0.05215711
   0.25513773 -0.18424073 -0.42664417 -0.01637127]
 [-0.5418495   0.15934343 -0.52984181  0.24076688 -0.37244627 -0.02196182
   0.11557392  0.12049166  0.37237291  0.3859398 ]
 [ 0.04981456  0.14284886 -0.06274891 -0.41167464  0.42938979  0.5421537
   0.3535902   0.08659805 -0.3843801   0.39824708]
 [ 0.07654939 -0.10539463  0.30312404  0.03271038  0.12102419 -0.06809283
  -0.11557392 -0.09143834  0.42017591 -0.38142165]
 

12. Создать матрицу случайных чисел 5x5. Добавить к ней столбецы максимумов и минимумов по строкам. Получится матрица 5x7.

In [ ]:
random_matr = np.random.rand(5, 5)
max_min_matr = np.hstack((random_matr, np.max(random_matr, axis=1, keepdims=True), np.min(random_matr, axis=1, keepdims=True)))
print(max_min_matr)

[[0.69376652 0.83276727 0.95045642 0.00233516 0.46431719 0.95045642
  0.00233516]
 [0.85652272 0.05695352 0.5959171  0.82134422 0.85332702 0.85652272
  0.05695352]
 [0.00296518 0.9596992  0.7728406  0.4008448  0.13070354 0.9596992
  0.00296518]
 [0.8387505  0.47083977 0.21469465 0.03091816 0.94307578 0.94307578
  0.03091816]
 [0.41327675 0.34325277 0.23623265 0.46589853 0.90563273 0.90563273
  0.23623265]]


13. Вектор чисел от 1 до 51 преобразовать в вектор нечетных чисел и в вектор четных чисел, поменять их размерности, чтобы получились две матрица. Найти произведение этих матриц. Найти обратную матрицу эётого произведения.

In [ ]:
vector = np.arange(1, 52)
odd_vector = vector[vector % 2 != 0]
even_vector = vector[vector % 2 == 0]
odd_matr = odd_vector.reshape(8, 3)
even_matr = even_vector.reshape(3,8)
product_matr = np.dot(odd_matr, even_matr)
inverse_matr = np.linalg.inv(product_matr)
print(inverse_matr)

14. Создать 8x8 матрицу и заполнить её в шахматном порядке нулями и единицами.

In [ ]:
chessboard_matr = np.zeros((8, 8), dtype=int)
chessboard_matr[1::2, ::2] = 1
chessboard_matr[::2, 1::2] = 1
print(chessboard_matr)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
